package com.nflapp.data.local

import androidx.room.TypeConverter
import com.nflapp.data.remote.PastGameDto
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * Serialization happens inside the function bodies on purpose: Room's KSP
 * processor cannot resolve members generated by the kotlinx.serialization
 * plugin, so they must not appear in declaration types.
 */
class Converters {
    @TypeConverter
    fun mapToString(value: Map<String, Double>): String = json.encodeToString(value)

    @TypeConverter
    fun stringToMap(value: String): Map<String, Double> = json.decodeFromString(value)

    @TypeConverter
    fun pastGamesToString(value: List<PastGameDto>): String = json.encodeToString(value)

    @TypeConverter
    fun stringToPastGames(value: String): List<PastGameDto> = json.decodeFromString(value)

    private companion object {
        val json = Json { ignoreUnknownKeys = true }
    }
}
